urls=[
    {
        "url": "https://www.sverigesradio.se/artikel/pontus-tycker-alla-borde-bada-kallbad",
        "title": "Pontus tycker alla borde bada kallbad",
        "language": "Swedish",
        "content": "Pontus Josefsson bor i Luleå. Han har en ovanlig hobby. Han badar i en isvak varje dag. Han gör alltså hål i isen och hoppar i vattnet. Nu har han badat i isvak i över 80 dagar i rad. Han säger till P4 Norrbotten att han får en känsla av att vara oslagbar när han badat i iskallt vatten. – Efteråt så känns det som att du kan ta över världen lite grann. Även om han är van vid att bada i iskallt vatten så är det en chock för kroppen att komma i vattnet, säger han. Då gäller det att andas djupt. – Då tar man några djupa andetag först bara för att få ner den där chocken. Den kommer alltid. Den kommer man aldrig ifrån. Att någon gång bada kallbad är ganska vanligt bland svenskar. Och institutet för språk och folkminnen har beslutat att kallbad är en del av svenskt kulturarv. Pontus Josefsson tycker att alla borde prova på att bada i en isvak på vintern. –"
    },
    {
        "url": "https://www.sverigesradio.se/artikel/4875506",
        "title": "Viktig tradition med vinterbad",
        "language": "Swedish",
        "content": "För sjunde året i rad badade hundratals i Haverdal. Fyra grader var det i havet men det stoppade inte de frusna, mycket glada julfirarna. Traditionen kommer från en idé av Nils Lundgren som när syskonen badade på skottdagen retade NIls eftersom han inte var tuff nog att våga bada. Då var Nils åtta år och bestämde sig för att bada på julafton, varje år. - Nu känns det lite som en dum idé, men det är en tradition som växt, säger han och skrattar. Familjen Holmin har badat fler år i rad och är mycket nöjda med årets julbad. - Jag har tänkt på det hela året sedan förra året, säger Joakim Holmin. -Man blir jättepigg, det är härligt hela dagen sedan, säger Josefina Holmin. P4 Halland sänder nyheter, väder, trafik, sport och välkänd musik. En lokal kanal med ditt län i fokus."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/bada-utomhus-hela-vintern-allt-mer-populart",
        "title": "Bada utomhus hela vintern allt mer populärt",
        "language": "Swedish",
        "content": "Många tycker om att bada utomhus hela vintern. Det har blivit allt mer populärt. En som badar varje dag är 12-åriga Ebba. – Känslan i kroppen är så himla skön, men på nåt sätt uppiggande och det finns inget bättre sätt att starta sin dag på. Det sade Ebba till SVT . Ebba är tolv år och bor i Tibro i Västra Götaland. Hon har badat varje morgon före skolan, hela hösten och vintern. När det är is gör hon hål i isen och hoppar i. Vinterbad blir allt mer populärt. Tusentals svenskar vinterbadar. Det finns inte så mycket forskning om vinterbad , bara några studier. Men det kan vara bra för hälsan. Pirkko Huttunen är forskare från Finland. Hon säger till SVT att vinterbad kan hjälpa människor med reumatism, mot smärta och inflammation. Många vinterbadare säger att de blir piggare och gladare och känner mindre stress. Men det kan vara farligt för personer med sjukdomar i hjärtat och blodkärlen. Blodtrycket går upp när man går ner i kallt vatten. Det finns tävlingar i vinterbad . Föreningen \"Mörkret och kylans glada vänner\" ordnar Skandinaviska Mästerskapen i Vintersim i Skellefteå. Det har de gjort i tio år. I år blir det ingen tävling på grund av coronapandemin, men föreningen skriver att intresset växer. De senaste åren har ungefär 400 personer från flera länder varit med i tävlingen. Ebba i Tibro vinterbadar fast det är mer än 10 minusgrader kallt. Hon kommer att fortsätta bada till sommaren. – Gud, det känns som om jag flyger, det känns som jag svävar, haha, så coolt! Lite kallt, men det är jätteskönt! Det säger 12-åriga Ebba till SVT."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/6601761",
        "title": "Vinterbad sätter fart på dina hormoner",
        "language": "Swedish",
        "content": "Att bada kallt ger en kortvarig stressreaktion i kroppen. Det är bra för kroppen om du inte har problem med hjärtat, säger hälsokreatören Malin Lundskog. Vinterbad är ett fenomen som förekommer regelbundet i Ryssland, Kina, Nordamerika och Norden och sägs vara bra för hälsan. Malin Lundskog arbetar med hälsa och är själv en van vinterbadare. – Det är en chock för kroppen. Det blir en stressreaktion men det är en kortvarig stress, som inte är farlig. Det sätter kroppen i beredskap och blir ett nyårsfyrverkeri av hormoner. En explosion av bra grejor, säger hon. Filip Kruse filip.kruse@sverigesradio.se P4 Göteborg är på plats där det händer för att ge dig lokala nyheter, väder, trafik, sport och välkänd musik. Lyssna direkt."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/7132431",
        "title": "Morgongänget testade vinterbad",
        "language": "Swedish",
    "content": "En impulshandling som resulterade med ett dopp i havet. Det hördes i onsdagens morgonprogram, där Tommy och Peter slog upp en vak i havet med sina egna kroppar. – Jag är verkligen inte så stöddig längre. Nu gör vi rätt direkt, det blir bara en jäkla tagning av detta, hör man Tommy Öster ropa. Vinterbad är en poppis hobby för många i Västsverige. Men för morgonredaktionen på P4 Väst fick det ett svalt, eller kanske snarare iskallt, mottagande. Vill du se en film från badet, klicka här . Nu återstår att se om P4 Göteborg och övriga P4-Sverige följer det kalla exemplet. Tommy Öster och Peter Olsson gomorron.vast@sverigesradio.se 0522 67 00 25 P4 Väst ger dig lokala nyheter, väder, trafik, sport och välkänd musik. Det senaste från Bohuslän, Norra Älvsborg och Dalsland."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/7398727",
        "title": "Kalla dopp lockar allt fler",
        "language": "Swedish",
        "content": "En ny generation upptäcker isvakar och kallbadhus. Men handlar det om välbefinnande eller prestation? På sociala medier finns tiotusentals bilder med hashtaggar som #winterswimming och #wildswimming. Att kalla bad har blivit en nygammal trend är något som också rutinerade vinterbadare märker av. - Det har blivit en hajp, det märks i dambastun där det oftast är knökfullt nuförtiden, säger Lena Moegelin , som vinterbadar i Nacka. Sociologen Pelle Pelters ser en logik i att allt fler lockas av de kalla vattnen. - De passar i en tid där vi ställer stora krav på oss själva, att prestera. Det är ett sätt bemästra både sig själv och naturen. Men andra ser istället vinterbad som en motkraft mot stress och en uppkopplad tillvaro, en form av mindfulness. Reporter: Nina Benner nina.benner@sverigesradio.se P1:s veckomagasin om Sverige och världen – politik, trender och analyser. Söndag 09.03 med repris samma kväll efter 22-nyheterna"
    },
    {
        "url": "https://www.sverigesradio.se/artikel/6851442",
        "title": "Goda hälsoeffekter vid kallbad",
        "language": "Swedish",
        "content": "Minst tre gånger i veckan går han ner i det tregradiga vattnet. För Arne Blidkvist har det blivit rutin att bada kallbad - och han märker av de positiva hälsoeffekterna. Tre grader. Så kallt är vattnet i Kypesjön där folk badar året om. Forskning visar på att kallbad kan ha positiva effekter för hälsan. Arne Blidkvist kallbadar minst tre gånger i veckan. - För fyra, fem år sedan mådde jag väldigt dåligt. Idag mår jag mycket bättre. Att sitta här och titta ut över den fina naturen är fantastiskt fint, säger han. Linus Dahlbäck linus.dahlback@sr.se P4 Sjuhärad håller dig uppdaterad med lokala nyheter, väder, trafik, sport och välkänd musik. Din lokala kanal – varje dag, året runt."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/7368673",
        "title": "Vinterbadarna: \"Varm känsla i kroppen\"",
        "language": "Swedish",
        "content": "Vinterbad kan ha positiva effekter på hälsan även om de vetenskapliga studierna är få, menar Linköpingsprofessorn Fredrik Nyström. Vinterbadarna Jane och Peter Hjelmqvist från Norrköping badar varje vecka och berättar om en värme i kroppen som infinner sig efter badet. – Skandinaviska beteenden som vinterbad och bastubad är relativt obeforskade områden men min köldstudie visar att kyla ökar energiförbrukningen vilket talar för vinterbad, säger Fredrik Nyström, professor i internmedicin vid Linköpings universitet. Lina Hedmark lina.hedmark@sverigsradio.se P4 Östergötland P4 Östergötland är kanalen med lokala nyheter, väder, trafik, sport och välkänd musik. Heltäckande bevakning där du bor."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/vinterbadsexpertens-tips-i-kylan-da-bor-man-kolla-med-lakare",
        "title": "Vinterbadsexpertens tips i kylan: Då bör man kolla med läkare",
        "language": "Swedish",
        "content": "Det är riktigt kallt i Sverige och i Varberg seglar havstemperaturen runt nollan. Det hindrar inte många vinterbadare att ta sig ett dopp – men är det säkert? Vinterbadsexperten Per Tjernström berättar vad du behöver tänka på, vad som händer med kroppen och när du behöver uppsöka läkare. Alma Tallborn Aringskog alma.aringskog@sverigesradio.se P4 Halland sänder nyheter, väder, trafik, sport och välkänd musik. En lokal kanal med ditt län i fokus."
        },
    {
        "url": "https://www.sverigesradio.se/artikel/vinterbad-trendar-men-an-vet-vi-lite-om-halsoeffekterna",
        "title": "Vinterbad trendar – men än vet vi lite om hälsoeffekterna",
        "language": "Swedish",
        "content": "Det är många som vinterbadar nu. Kanske kan trenden stimulera mer forskning om vinterbadandets hälsoeffekter, för om detta vet vi ännu ganska lite. Kanske är det en pandemieffekt, där många söker äventyr och utmaningar på hemmaplan, som gör att vinterbad nu är en trend. Ännu är hälsoeffekterna av vinterbad vetenskapligt väldigt outforskade – men Thérese Grane vid Simsjön utanför Skövde upplever att kalla bad ger tydliga hälsovinster. – Mycket är ju stress, att man känner att man kommer ner i varv, att man nästan liksom \"badar av sig\". Man släpper allting annat: ilska, sorg, rädsla, det finns liksom inte alls när vi är i närvaro. Då är det bara den här kylan, andningen, kroppen som finns. En oönskad känsla av vardagsstress utkonkurreras på ett ögonblick av den extrema köldchock som vinterbad innebär. Vårt omedelbara fysiologiska svar: stresshormoner som manar till flykt eller strid, och ett ökat blodtryck när blodkärlen drar ihop sig för att spara värme. Så länge man inte lider av underliggande sjukdomar som hjärt-kärlsjukdom blir det här kärlgymnastik som kroppen klarar fint. Men vinterbads hälsoeffekter är ännu väldigt obeforskade, så det stora allmänintresset nu lär leda till kommande studier, hoppas och tror hjärtforskaren Katarina Stening Ehrenborg vid Lunds universitet. – Om man tänker sig de här doppen där man bara går i och är i några sekunder och sedan kommer upp igen. Så som jag har förstått av de som vinterbadar, så får de en känsla av stor lycka efteråt, säger hon. – Jag tror att det här adrenalinpåslaget som man får av kylan kopplat med endorfiner tillsammans efteråt gör att man känner sig väldigt alert, man mår väldigt bra. Och när man mår bra blir man ju avslappnad och då får man minskad stress, och det är bra för hjärta och kärl. Alltså, den samlade förståelsen är nog ändå att det är positivt eftersom man tycker att det är härligt, och det är nog sällan det är farligt, säger Katarina Stening Ehrenborg. Här mer i Vetenskapsradion Hälsa. Ylva Carlqvist Warnborg vet@sverigesradio.se Få dagliga vetenskapsnyheter om den senaste forskningen och hur den påverkar dig – med Vetenskapsradion nyheter i Sveriges Radio P1. I Sveriges Radio P1 kl 06.34, 07.36, 08.36"
        },
  
    {
        "url": "https://www.svt.se/nyheter/inrikes/busch-forbjud-burka-och-niqab-pa-allman-plats",
        "title": "Busch - Förbjud burka och niqab på allmän plats",
        "language": "Swedish",
        "content": "KD-ledaren Ebba Busch anser att burka och niqab ska totalförbjudas i offentliga miljöer. – Man bör kunna mötas på riktigt om man är på gatan, om man handlar på torget, i Ica-butiken eller tar barnen till vårdcentralen. Då vill jag inte möta någon som har skylt hela sitt ansikte, säger hon till Aftonbladet . Förbudet ska omfatta allmänna platser som exempelvis gator, torg, köpcentrum och vårdinrättningar. Enligt Busch är niqab och burka ett uttryck för strikt tolkning av islam som är oförenlig med svenska värderingar. – Islam måste anpassa sig i Sverige. Man kan vara stolt svensk muslim, kristen, jude, ateist, men det är grundläggande svenska värderingar som måste gälla oss alla. Liberalernas partiledare Simona Mohamsson kommenterar Buschs utspel: ”Burka och niqab är kvinnoförtryckande plagg som bygger på idén om att kvinnan inte ska synas i det offentliga rummet. För Liberalerna är det viktigt att de som utövar religiöst förtryck – till exempel slöjtvång – straffas av samhället”, skriver hon i ett sms till Aftonbladet. Förslaget att förbjuda burka och niqab i offentliga miljöer är en del av ett utvecklingsarbete som en arbetsgrupp inom KD tagit fram inför stämman senare i höst. Det har inte förankrats hos övriga Tidöpartier. Ebba Busch konstaterar att samhället varken kan eller ska kontrollera vad folk gör i hemmet. – Men burkan hör inte hemma i Sverige och vi ska inte bana väg för den. Vi ska mota Olle i grind här. Uppdaterad 12 oktober 2025 kl 16:04 Publicerad 12 oktober 2025 kl 12:09 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
        {
        "url": "https://www.svt.se/nyheter/utrikes/hamas-gisslan-slapps-pa-mandag",
        "title": "Hamas: Gisslan släpps på måndag",
        "language": "Swedish",
        "content": "Terrorstämplade Hamas kommer att påbörja frisläppandet av israeliska gisslan på måndag morgon. Det säger det högt uppsatta Hamasbefälet Osama Hamdan till nyhetsbyrån AFP. Enligt uppgörelsen med Israel i torsdags ska Hamas frige gisslan senast klockan 12 på måndag lokal tid, skriver BBC. 48 personer som togs som gisslan för två år sedan är fortfarande kvar i Gaza. 20 av dem bedöms vara vid liv. De ska släppas i utbyte mot omkring 2 000 palestinska fångar – exakt vilka är en fråga som ännu diskuteras. Publicerad 12 oktober 2025 kl 07:16 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
   
       {
        "url": "https://www.svt.se/nyheter/lokalt/varmland/en-till-sjukhus-efter-villabrand-i-kil-utreds-som-mordbrand",
        "title": "En till sjukhus efter villabrand i Kil – utreds som mordbrand",
        "language": "Swedish",
        "content": "En person är förd till sjukhus med oklart skadeläge efter en villabrand i Kil under söndagsmorgonen. Huset var helt övertänt när räddningstjänsten kom fram och det gick inte att rädda. Tidigt under söndagsmorgonen larmades räddningstjänsten till Högboda i Kils kommun. Det rörde sig om en villa som hade börjat brinna. Enligt polisen ska två personer ha tagit sig ut ur fastigheten och minst en person är förd till sjukvården men skadeläget är okänt. – En person verkar har hoppat ut från fönstret, säger Anders Dahlman, polisens presstalesperson. Enligt polisen ska ingen person vara kvar i byggnaden. Räddningstjänsten är kvar på plats under söndagen och polisen kommer genomföra teknisk undersökning. – Vi kommer inte kunna komma dit för undersökning idag, räddningstjänsten är inte klara och det är nog fortfarande för varmt där än. Så fort de är klara spärrar vi av för teknisk undersökning, säger Anders Dahlman på polisen under söndagsförmiddagen. Det är oklart varför branden uppstod. Händelsen utreds i nuläget som mordbrand. Uppdaterad 12 oktober 2025 kl 11:41 Publicerad 12 oktober 2025 kl 08:50 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.sverigesradio.se/artikel/4875506",
        "title": "Viktig tradition med vinterbad",
        "language": "Swedish",
        "content": "För sjunde året i rad badade hundratals i Haverdal. Fyra grader var det i havet men det stoppade inte de frusna, mycket glada julfirarna. Traditionen kommer från en idé av Nils Lundgren som när syskonen badade på skottdagen retade NIls eftersom han inte var tuff nog att våga bada. Då var Nils åtta år och bestämde sig för att bada på julafton, varje år. - Nu känns det lite som en dum idé, men det är en tradition som växt, säger han och skrattar. Familjen Holmin har badat fler år i rad och är mycket nöjda med årets julbad. - Jag har tänkt på det hela året sedan förra året, säger Joakim Holmin. -Man blir jättepigg, det är härligt hela dagen sedan, säger Josefina Holmin. P4 Halland sänder nyheter, väder, trafik, sport och välkänd musik. En lokal kanal med ditt län i fokus."
        },
        {
        "url": "https://www.svt.se/nyheter/inrikes/hatt-effekten-ar-utraderad",
        "title": "Centerpartiet saknar Hatt-effekt trots nya ledarskapet",
        "language": "Swedish",
        "content": "Efter drygt fem månader med Anna-Karin Hatt vid rodret är Centerpartiet tillbaka på samma nivå som när hon valdes. Den ”Hatt-effekt” som partikamraterna hoppades på lyser med sin frånvaro. En förklaring är att de saknar en trovärdig parlamentarisk strategi för att få igenom sin politik. När partiledarna drabbar samman i kvällens Agenda gör de det i ljuset av att det är stiltje i opinionen. Trots veckor av budgetutspel, ett oroligt omvärldsläge och ett högt tonläge i sociala medier är alla förändringar inom felmarginalen. Värt att notera är dock att oppositionens övertag håller i sig. Och det trots att Tidöpartierna lagt en mycket expansiv valbudget där nära 50 miljarder går till att stärka hushållen. Men det miljardregnet känner väljarna inte av än. Många är fortsatt pressade och det finns en pessimism bland hushållen som missgynnar regeringen. Enligt den senaste mätningen från Novus tycker 61 procent av väljarna att Sverige är på väg åt fel håll. Det är en av de saker som Tidöpartierna behöver vända om de ska lyckas få en mandatperiod till i Rosenbad. För Moderaterna är utgångsläget dystert. Inte sedan 1978 har de legat så här lågt i oktober året före valet. Ett annat parti som har skäl att vara besvikna är Centerpartiet. När Anna-Karin Hatt (C) valdes till partiledare fanns stora förhoppningar på en tydlig ”Hatt-effekt”. Partistrategerna såg framför sig att hon skulle göra så kallade ”Magda-moderater” till ”Hatt-sossar”, alltså att välutbildade och välavlönade liberala storstadsväljare skulle föredra henne framför Magdalena Andersson (S). Men några sådana tendenser syns inte alls än – tvärtom har C åter ett flöde till S precis som tidigare under mandatperioden. En förklaring är att de har svårt att göra sig relevanta som minsta parti i opposition. En annan är det utomordentligt svaga stödet i samtliga sakfrågor. Det problemet är Anna-Karin Hatt högst medveten om, det är därför hon betonar vikten av sakpolitisk förnyelse. Men även om partiet lägger allt sitt krut på sakfrågorna går det inte att komma ifrån att de saknar en strategi för att få igenom dem. Det enda besked hon har gett är att all form av samverkan med SD är utesluten. Och skälet är enligt Hatt SD:s människosyn. Partiets tidigare insikt om att det är vanskligt att göra motståndet mot ett annat parti till sin främsta profilfråga verkar vara bortglömd. Det är elva månader till valet och mycket kan hända men om C blir minst på Anderssons sida har de ett svagt förhandlingsläge vid en eventuell vänsterseger. Särskilt förstås om de inte ens behövs för en rödgrön majoritet"
        },
        {
        "url": "https://www.svt.se/nyheter/inrikes/allt-utom-rekorduppvarmning-vore-en-verklig-nyhet-2025",
        "title": "Europa drabbas av rekordvärme och smältande glaciärer",
        "language": "Swedish",
        "content": "Det är svårt att hänga med i alla klimatrekord som slogs 2024. Och rekorden fortsätter tyvärr i år. Europa ligger mitt i klimatförändringarnas brännpunkt – och det står fullkomligt klart att vi lider svårt – redan under en global uppvärmning som fortfarande ligger under Parisavtalets 1,5 grad. 2024 var det varmaste året i Europa som någonsin uppmätts. Jag tar det igen, för säkerhets skull. Det varmaste året som någonsin uppmätts. Europa är kontinenten där den globala uppvärmningen går snabbast i världen – dubbelt så snabbt som det globala genomsnittet. Ändå är EU:s klimatövervakningsorgans pressbriefing över Europas klimat en rätt avslagen historia. Det är svårt att hitta en nyhet efter över tio år av nästan precis samma berättelse. Men det är bedrägligt att inte reagera. För är det nåt som står klart nu, är det att även vi européer får allt svårare att hantera konsekvenserna av att vara en hotspot för klimatet. Trots att vi hör till världens rikaste länder. Över 400 000 européer drabbades av svåra stormar och översvämningar förra året, bara i Valencia i oktober dog över 200 personer. Men bara hälften av städerna i Copernicus granskning har ännu upprättat en plan för klimatanpassning till det nya normala. Det är ändå ett stort fall framåt jämfört med tidigare. Och rekorden fortsätter 2025 – månad efter månad, på land och till havs. Mars i år var den varmaste uppmätta hittills i Europa, och havsisen i både Arktis och Antarktis smälte rekordartat. I ett försök att hitta ljusglimtar i den här extremt varma soppan, blir jag glad när Nina Kirchner, professor i glaciologi, tar sig ner till ett redan vårlikt Nikkaluokta. Hon berättar att deras nya mätningar av rekordsmältande svenska glaciärer visar något helt annat än 2024. Just nu är det dubbelt så mycket snö på referensglaciärerna som vanligt. Blir sommaren i nordligaste Sverige inte rekordvarm, tror hon att de faktiskt kan hämta sig en smula. Men innan jag hinner bli uppeldad över den oväntade nyheten säger hon: – Ta nu inte det till intäkt för att glaciärerna inte smälter. Det är därför det är bra att vi har mätt dem i över 80 år. Vädret varierar från år till år, men den långsiktiga trenden är tydlig – många är på väg att försvinna. Men glaciärexperten och aktivisten Erik Huss har inte gett upp, trots ett misslyckat försök i höstas att rädda den mäktiga Kårsaglaciären, med en ullduk över snön. Innan han hann fram hade glaciärtungan redan kollapsat. – Det här problemet är så allvarligt och måste lyftas. Så nu växlar jag upp istället, säger han och packar noggrant – för en helt ny glaciär."
        },
        {
        "url": "https://www.sverigesradio.se/artikel/efter-dronarlarm-danmark-overvager-att-aktivera-natos-artikel-4",
        "title": "Rasmusson: Danmark överväger att aktivera Natos artikel 4",
        "language": "Swedish",
        "content": "Den danska försvarsministern Troels Lund Poulsen säger under presskonferensen att de ser incidenten som ett hybridangrepp och att de överväger att aktivera Natos artikel 4. ”Vi vet inte varför de inte har skjutits ner, det är en fråga som många har ställt sig”, säger David Rasmusson, Sveriges Radios Danmarkskorrespondent, som var på pressträffen i Danmark. Justitieministern Peter Hummelgaard sa även under pressträffen att man ska köpa in ny utrustning för att kunna göra det lättare att ta ner drönare. Ekot ekot@sverigesradio.se"
        },
        {
        "url": "https://www.sverigesradio.se/artikel/danmark-kommer-inte-aktivera-natos-artikel-4",
        "title": "Danmark kommer inte aktivera Natos artikel 4",
        "language": "Swedish",
        "content": "Danmark kommer inte att aktivera Natos artikel 4 efter drönarobservationerna runt danska flygplatser, det meddelar landets utrikesminister Lars Løkke Rasmussen idag. Det var något som Danska försvarsministern tidigare i veckan sade att man övervägde att göra. Enligt Lars Løkke Rasmussen är samarbetet inom Nato när det gäller drönarfrågan redan gott och han ser inga behov av ett särskilt möte om detta. Tatiana Kireeva tatiana.kireeva@sverigesradio.se P4 Malmöhus är på plats där det händer för att ge dig lokala nyheter, väder, trafik, sport och välkänd musik. Lyssna direkt. Helsingborg 103,2 MHz ● Hörby 89,5 MHz ● Malmö 102,0 MHz ● Trelleborg 103,7 MHz ● Ystad 103,0 MHz"
        },
        {
        "url": "https://www.sverigesradio.se/artikel/greta-thunberg-berattar-om-vald-och-krankningar-i-israels-fangelse",
        "title": "Greta Thunberg berättar om våld och kränkningar i Israels fängelse",
        "language": "Swedish",
        "content": "Aktivisten Greta Thunberg säger till Aftonbladet att hon blev slagen, sparkad och kallad \"hora\" när hon satt i fängelse i Israel. Hon berättar också att aktivisterna inte fick vatten. Greta Thunberg och flera hundra andra aktivister försökte åka med båtar till Gaza. Ungefär tio aktivister var från Sverige. Aktivisterna ville ge hjälp till folket och protestera mot att Israel blockerar området. Israelisk militär stoppade båtarna i början av oktober, och tog aktivisterna till Israel. Där satt de i fängelse i flera dagar. Greta Thunberg säger att hon blev utsatt för våld och släpad på marken. Hon berättar att de placerade en israelisk flagga på henne. När flaggan nuddade henne blev hon sparkad. – Den här flaggan, de placerar den liksom så att den ska nudda vid mig. Och när den nuddar vid mig så säger de \"rör inte flaggan!\", och så sparkar de mig. Hon berättar också att hon sattes för sig själv och blev förolämpad. Hon säger till Aftonbladets reporter att de kallade henne \"hora\" på svenska. – Bland annat det som jag sa, \"lilla hora\" och så. På svenska? – Ja. En annan svensk aktivist , Vincent Storm, bekräftar Gretas berättelse. Han säger till TT att aktivisterna inte fick tillräckligt med mat eller vatten. Personal från Sveriges Utrikesdepartement UD träffade aktivisterna i fängelset. Greta Thunberg och Vincent Storm är kritiska. De säger att UD inte berättade för andra hur dåligt aktivisterna blev behandlade. De tycker också att Sverige inte hjälpte till lika mycket som andra länder. Vincent Storm säger till exempel att andra aktivister fick vatten från sina länder. UD och utrikesministern skriver till P3 Nyheter att ambassaden försökte ge mat och vatten till svenskarna, men att fängelset inte tillät det. De skriver också att de tar uppgifterna om dålig behandling av aktivisterna på stort allvar, och kontaktar israeliska myndigheter om det."
        },
        {
        "url": "https://www.sverigesradio.se/artikel/mikael-raddade-en-skadad-orn",
        "title": "Mikael räddade en skadad örn",
        "language": "Swedish",
        "content": "Mikael Anjou var ute i skogen och plockade svamp i Vimmerby i Småland. Han såg en stor fågel, en havsörn, som var skadad. Han hjälpte den att komma till en viltvårdare. Mikael Anjou berättar för P4 Kalmar att örnen inte kunde flyga, den flaxade upp och ramlade ner igen. – Det är en örn som verkar ha svårt att lyfta, jag märkte att han flög kort och så landade han och damp ner i backen. Han lyckades fånga örnen och körde den till viltvårdare. Nu har Mikael fått veta hur det gått för örnen. Örnen hade blivit magrare, men den kommer att klara sig och kan snart släppas ut i naturen igen. Det gör Mikael glad. – Man blir ju glad, alltså ja, man blir glad. Nu när man vet att den var uthungrad och att det var en årsunge ordentligt, så är det ju ännu mer liksom, hjärtat värms ju av det."
        },
        {
        "url": "https://www.sverigesradio.se/artikel/svenskar-dricker-mindre-alkohol-an-forut",
        "title": "Svenskar dricker mindre alkohol än förut",
        "language": "Swedish",
        "content": "Folk i Sverige dricker mindre alkohol än tidigare. De senaste fem åren har drickandet minskat med 6,5 procent. Det visar en rapport från Centralförbundet för alkohol- och narkotikaupplysning. Vi har tidigare rapporterat att ungdomar dricker mindre alkohol än tidigare. Simon Woldekidan och Joakim Strömberg går sista året på gymnasiet i Stockholm. De säger att många ungdomar ändå brukar festa och dricka alkohol. – Jag skulle inte säga att jag märker av någon skillnad. Vi är ändå ute och man krökar ju på en del liksom. – Jag tänker samma. Det är väl någon fest här och där. Enligt rapporten handlar svenskar också mindre alkohol när de reser utomlands, jämfört med tidigare. Det är inte längre så mycket billigare att köpa alkohol utomlands än i Sverige, säger Björn Trolldal som skrivit rapporten. – Det har blivit mindre lönsamt att handla alkohol i andra länder. Han säger att fler handlar på Systembolaget i Sverige. – Systembolaget har ökat sin försäljning och sin andel av konsumtionen. Gunilla Olofsson handlar vin på Systembolaget. Hon är pensionär och tycker om att dricka vitt vin, säger hon . – Jag har köpt vitt vin som vi tycker väldigt mycket om. Nämen jag dricker inte särskilt mycket."
        },
        {
        "url": "https://www.sverigesradio.se/artikel/det-gar-daligt-for-sverige-i-kvalet-till-fotbolls-vm",
        "title": "Tränaren för herrlandslaget i fotboll får sparken",
        "language": "Swedish",
        "content": "Det går inte bra för Sveriges herrlandslag i fotboll. Igår förlorade de sin tredje match i rad i kvalet till VM. Risken är stor att Sverige inte får spela i fotbolls-VM nästa år. Nu får tränaren Jon Dahl Tomasson sparken. Sverige förlorade en match mot Kosovo med 1-0 igår kväll, på fotbollsarenan Ullevi i Göteborg. Publiken var besviken och buade. Sverige har bara fått en poäng på fyra matcher i kvalet och ligger sist i sin grupp. Sverige har två matcher kvar, mot Slovenien och Schweiz, men det blir svårt att få ihop tillräckligt med poäng för att gå vidare. Sveriges herrlandslag var inte med i VM 2022 eller EM 2024. Nu är risken att de missar VM 2026 också. Många fans och experter har sagt att tränaren borde lämna sitt jobb när det går så här dåligt. Och nu säger Svenska fotbollförbundet att Jon Dahl Tomasson får sparken. Förbundets ordförande Simon Åström skriver att det behövs en ny ledare för att landslaget kanske ska lyckas nå VM nästa år. Radiosportens expert Johan Elmander säger att det inte fanns något annat val. Nu måste man försöka hitta nya lösningar, säger han. – Efter de resultat som har varit den senaste tiden så fanns det egentligen inte någon annan utväg. Sen så är det alltid tråkigt när det händer, men någonstans så måste man försöka gå vidare och hitta nya lösningar. Det här är första gången Svenska fotbollförbundet sparkar en tränare för Sveriges landslag. Jon Dahl Tomasson har bara varit Sveriges tränare i ungefär ett och ett halvt år. Det är inte klart vem som ska ta över jobbet. Sverige spelar nästa match i VM-kvalet den 15 november, mot Schweiz."
        },
        {
        "url": "https://www.sverigesradio.se/artikel/ny-serie-om-scorsese-later-tittaren-komma-masterregissoren-inpa-livet",
        "title": "Ny serie om Scorsese låter tittaren komma mästerregissören inpå livet",
        "language": "Swedish",
        "content": "Regissören och manusförfattaren Rebecca Miller har fått tillgång till Martin Scorseses eget arkiv med bilder från barndomen, och från hela hans karriär. Dokumentären visar en ödmjuk stor-regissör som berättar om både misslyckanden och de stora framgångarna. I Kulturnytts intervju berättar Rebecca Miller om vad som gör Martin Scorsese till regissören som gjort intressant och spännande film ända sedan 60-talet, med några få undantag i början av karriären. Björn Jansson bjorn.jansson@sverigesradio.se Nyheter från kulturredaktionen, med reportage, nyheter och recensioner. Kulturnytt sänder i P1, P2 och P4 måndag–fredag. P1 Kultur sänder i P1 tisdag–fredag 13.00. Kulturkollen sänder i P1 söndagar 12.55 och måndagar 11.55"
        }


]