urls=[
    {
        "url": "https://www.sverigesradio.se/artikel/pontus-tycker-alla-borde-bada-kallbad",
        "title": "Pontus tycker alla borde bada kallbad",
        "language": "Swedish",
        "content": "Pontus Josefsson bor i Luleå. Han har en ovanlig hobby. Han badar i en isvak varje dag. Han gör alltså hål i isen och hoppar i vattnet. Nu har han badat i isvak i över 80 dagar i rad. Han säger till P4 Norrbotten att han får en känsla av att vara oslagbar när han badat i iskallt vatten. – Efteråt så känns det som att du kan ta över världen lite grann. Även om han är van vid att bada i iskallt vatten så är det en chock för kroppen att komma i vattnet, säger han. Då gäller det att andas djupt. – Då tar man några djupa andetag först bara för att få ner den där chocken. Den kommer alltid. Den kommer man aldrig ifrån. Att någon gång bada kallbad är ganska vanligt bland svenskar. Och institutet för språk och folkminnen har beslutat att kallbad är en del av svenskt kulturarv. Pontus Josefsson tycker att alla borde prova på att bada i en isvak på vintern. –"
    },
    {
        "url": "https://www.sverigesradio.se/artikel/4875506",
        "title": "Viktig tradition med vinterbad",
        "language": "Swedish",
        "content": "För sjunde året i rad badade hundratals i Haverdal. Fyra grader var det i havet men det stoppade inte de frusna, mycket glada julfirarna. Traditionen kommer från en idé av Nils Lundgren som när syskonen badade på skottdagen retade NIls eftersom han inte var tuff nog att våga bada. Då var Nils åtta år och bestämde sig för att bada på julafton, varje år. - Nu känns det lite som en dum idé, men det är en tradition som växt, säger han och skrattar. Familjen Holmin har badat fler år i rad och är mycket nöjda med årets julbad. - Jag har tänkt på det hela året sedan förra året, säger Joakim Holmin. -Man blir jättepigg, det är härligt hela dagen sedan, säger Josefina Holmin. P4 Halland sänder nyheter, väder, trafik, sport och välkänd musik. En lokal kanal med ditt län i fokus."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/bada-utomhus-hela-vintern-allt-mer-populart",
        "title": "Bada utomhus hela vintern allt mer populärt",
        "language": "Swedish",
        "content": "Många tycker om att bada utomhus hela vintern. Det har blivit allt mer populärt. En som badar varje dag är 12-åriga Ebba. – Känslan i kroppen är så himla skön, men på nåt sätt uppiggande och det finns inget bättre sätt att starta sin dag på. Det sade Ebba till SVT . Ebba är tolv år och bor i Tibro i Västra Götaland. Hon har badat varje morgon före skolan, hela hösten och vintern. När det är is gör hon hål i isen och hoppar i. Vinterbad blir allt mer populärt. Tusentals svenskar vinterbadar. Det finns inte så mycket forskning om vinterbad , bara några studier. Men det kan vara bra för hälsan. Pirkko Huttunen är forskare från Finland. Hon säger till SVT att vinterbad kan hjälpa människor med reumatism, mot smärta och inflammation. Många vinterbadare säger att de blir piggare och gladare och känner mindre stress. Men det kan vara farligt för personer med sjukdomar i hjärtat och blodkärlen. Blodtrycket går upp när man går ner i kallt vatten. Det finns tävlingar i vinterbad . Föreningen \"Mörkret och kylans glada vänner\" ordnar Skandinaviska Mästerskapen i Vintersim i Skellefteå. Det har de gjort i tio år. I år blir det ingen tävling på grund av coronapandemin, men föreningen skriver att intresset växer. De senaste åren har ungefär 400 personer från flera länder varit med i tävlingen. Ebba i Tibro vinterbadar fast det är mer än 10 minusgrader kallt. Hon kommer att fortsätta bada till sommaren. – Gud, det känns som om jag flyger, det känns som jag svävar, haha, så coolt! Lite kallt, men det är jätteskönt! Det säger 12-åriga Ebba till SVT."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/6601761",
        "title": "Vinterbad sätter fart på dina hormoner",
        "language": "Swedish",
        "content": "– Att bada kallt ger en kortvarig stressreaktion i kroppen. Det är bra för kroppen om du inte har problem med hjärtat, säger hälsokreatören Malin Lundskog. Vinterbad är ett fenomen som förekommer regelbundet i Ryssland, Kina, Nordamerika och Norden och sägs vara bra för hälsan. Malin Lundskog arbetar med hälsa och är själv en van vinterbadare. – Det är en chock för kroppen. Det blir en stressreaktion men det är en kortvarig stress, som inte är farlig. Det sätter kroppen i beredskap och blir ett nyårsfyrverkeri av hormoner. En explosion av bra grejor, säger hon. Filip Kruse filip.kruse@sverigesradio.se P4 Göteborg är på plats där det händer för att ge dig lokala nyheter, väder, trafik, sport och välkänd musik. Lyssna direkt."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/7132431",
        "title": "Morgongänget testade vinterbad",
        "language": "Swedish",
    "content": "En impulshandling som resulterade med ett dopp i havet. Det hördes i onsdagens morgonprogram, där Tommy och Peter slog upp en vak i havet med sina egna kroppar. – Jag är verkligen inte så stöddig längre. Nu gör vi rätt direkt, det blir bara en jäkla tagning av detta, hör man Tommy Öster ropa. Vinterbad är en poppis hobby för många i Västsverige. Men för morgonredaktionen på P4 Väst fick det ett svalt, eller kanske snarare iskallt, mottagande. Vill du se en film från badet, klicka här . Nu återstår att se om P4 Göteborg och övriga P4-Sverige följer det kalla exemplet. Tommy Öster och Peter Olsson gomorron.vast@sverigesradio.se 0522 67 00 25 P4 Väst ger dig lokala nyheter, väder, trafik, sport och välkänd musik. Det senaste från Bohuslän, Norra Älvsborg och Dalsland."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/7398727",
        "title": "Kalla dopp lockar allt fler",
        "language": "Swedish",
        "content": "En ny generation upptäcker isvakar och kallbadhus. Men handlar det om välbefinnande eller prestation? På sociala medier finns tiotusentals bilder med hashtaggar som #winterswimming och #wildswimming. Att kalla bad har blivit en nygammal trend är något som också rutinerade vinterbadare märker av. - Det har blivit en hajp, det märks i dambastun där det oftast är knökfullt nuförtiden, säger Lena Moegelin , som vinterbadar i Nacka. Sociologen Pelle Pelters ser en logik i att allt fler lockas av de kalla vattnen. - De passar i en tid där vi ställer stora krav på oss själva, att prestera. Det är ett sätt bemästra både sig själv och naturen. Men andra ser istället vinterbad som en motkraft mot stress och en uppkopplad tillvaro, en form av mindfulness. Reporter: Nina Benner nina.benner@sverigesradio.se P1:s veckomagasin om Sverige och världen – politik, trender och analyser. Söndag 09.03 med repris samma kväll efter 22-nyheterna"
    },
    {
        "url": "https://www.sverigesradio.se/artikel/6851442",
        "title": "Goda hälsoeffekter vid kallbad",
        "language": "Swedish",
        "content": "Minst tre gånger i veckan går han ner i det tregradiga vattnet. För Arne Blidkvist har det blivit rutin att bada kallbad - och han märker av de positiva hälsoeffekterna. Tre grader. Så kallt är vattnet i Kypesjön där folk badar året om. Forskning visar på att kallbad kan ha positiva effekter för hälsan. Arne Blidkvist kallbadar minst tre gånger i veckan. - För fyra, fem år sedan mådde jag väldigt dåligt. Idag mår jag mycket bättre. Att sitta här och titta ut över den fina naturen är fantastiskt fint, säger han. Linus Dahlbäck linus.dahlback@sr.se P4 Sjuhärad håller dig uppdaterad med lokala nyheter, väder, trafik, sport och välkänd musik. Din lokala kanal – varje dag, året runt."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/7368673",
        "title": "Vinterbadarna: \"Varm känsla i kroppen\"",
        "language": "Swedish",
        "content": "Vinterbad kan ha positiva effekter på hälsan även om de vetenskapliga studierna är få, menar Linköpingsprofessorn Fredrik Nyström. Vinterbadarna Jane och Peter Hjelmqvist från Norrköping badar varje vecka och berättar om en värme i kroppen som infinner sig efter badet. – Skandinaviska beteenden som vinterbad och bastubad är relativt obeforskade områden men min köldstudie visar att kyla ökar energiförbrukningen vilket talar för vinterbad, säger Fredrik Nyström, professor i internmedicin vid Linköpings universitet. Lina Hedmark lina.hedmark@sverigsradio.se P4 Östergötland P4 Östergötland är kanalen med lokala nyheter, väder, trafik, sport och välkänd musik. Heltäckande bevakning där du bor."
    },
    {
        "url": "https://www.sverigesradio.se/artikel/vinterbadsexpertens-tips-i-kylan-da-bor-man-kolla-med-lakare",
        "title": "Vinterbadsexpertens tips i kylan: Då bör man kolla med läkare",
        "language": "Swedish",
        "content": "Det är riktigt kallt i Sverige och i Varberg seglar havstemperaturen runt nollan. Det hindrar inte många vinterbadare att ta sig ett dopp – men är det säkert? Vinterbadsexperten Per Tjernström berättar vad du behöver tänka på, vad som händer med kroppen och när du behöver uppsöka läkare. Alma Tallborn Aringskog alma.aringskog@sverigesradio.se P4 Halland sänder nyheter, väder, trafik, sport och välkänd musik. En lokal kanal med ditt län i fokus."
        },
    {
        "url": "https://www.sverigesradio.se/artikel/vinterbad-trendar-men-an-vet-vi-lite-om-halsoeffekterna",
        "title": "Vinterbad trendar – men än vet vi lite om hälsoeffekterna",
        "language": "Swedish",
        "content": "Det är många som vinterbadar nu. Kanske kan trenden stimulera mer forskning om vinterbadandets hälsoeffekter, för om detta vet vi ännu ganska lite. Kanske är det en pandemieffekt, där många söker äventyr och utmaningar på hemmaplan, som gör att vinterbad nu är en trend. Ännu är hälsoeffekterna av vinterbad vetenskapligt väldigt outforskade – men Thérese Grane vid Simsjön utanför Skövde upplever att kalla bad ger tydliga hälsovinster. – Mycket är ju stress, att man känner att man kommer ner i varv, att man nästan liksom \"badar av sig\". Man släpper allting annat: ilska, sorg, rädsla, det finns liksom inte alls när vi är i närvaro. Då är det bara den här kylan, andningen, kroppen som finns. En oönskad känsla av vardagsstress utkonkurreras på ett ögonblick av den extrema köldchock som vinterbad innebär. Vårt omedelbara fysiologiska svar: stresshormoner som manar till flykt eller strid, och ett ökat blodtryck när blodkärlen drar ihop sig för att spara värme. Så länge man inte lider av underliggande sjukdomar som hjärt-kärlsjukdom blir det här kärlgymnastik som kroppen klarar fint. Men vinterbads hälsoeffekter är ännu väldigt obeforskade, så det stora allmänintresset nu lär leda till kommande studier, hoppas och tror hjärtforskaren Katarina Stening Ehrenborg vid Lunds universitet. – Om man tänker sig de här doppen där man bara går i och är i några sekunder och sedan kommer upp igen. Så som jag har förstått av de som vinterbadar, så får de en känsla av stor lycka efteråt, säger hon. – Jag tror att det här adrenalinpåslaget som man får av kylan kopplat med endorfiner tillsammans efteråt gör att man känner sig väldigt alert, man mår väldigt bra. Och när man mår bra blir man ju avslappnad och då får man minskad stress, och det är bra för hjärta och kärl. Alltså, den samlade förståelsen är nog ändå att det är positivt eftersom man tycker att det är härligt, och det är nog sällan det är farligt, säger Katarina Stening Ehrenborg. Här mer i Vetenskapsradion Hälsa. Ylva Carlqvist Warnborg vet@sverigesradio.se Få dagliga vetenskapsnyheter om den senaste forskningen och hur den påverkar dig – med Vetenskapsradion nyheter i Sveriges Radio P1. I Sveriges Radio P1 kl 06.34, 07.36, 08.36"
        },
    {
        "url": "https://www.sverigesradio.se/artikel/7642206",
        "title": "Forskare om kallbad: Kan motverka fetma",
        "language": "Swedish",
        "content": "Eva Kleppe p4vastmanland@sverigesradio.se P4 Västmanland är kanalen som ger dig lokala nyheter, väder, trafik, sport och välkänd musik – varje dag, året runt. Lyssna direkt. På frekvensen 100,5. Vardagar 6.00-17.35. Under helger lokala nyheter och sport."
        }  ,
    {
        "url": "https://www.svt.se/nyheter/inrikes/busch-forbjud-burka-och-niqab-pa-allman-plats",
        "title": "Busch: Förbjud burka och niqab på allmän plats",
        "language": "Swedish",
        "content": "KD-ledaren Ebba Busch anser att burka och niqab ska totalförbjudas i offentliga miljöer. – Man bör kunna mötas på riktigt om man är på gatan, om man handlar på torget, i Ica-butiken eller tar barnen till vårdcentralen. Då vill jag inte möta någon som har skylt hela sitt ansikte, säger hon till Aftonbladet . Förbudet ska omfatta allmänna platser som exempelvis gator, torg, köpcentrum och vårdinrättningar. Enligt Busch är niqab och burka ett uttryck för strikt tolkning av islam som är oförenlig med svenska värderingar. – Islam måste anpassa sig i Sverige. Man kan vara stolt svensk muslim, kristen, jude, ateist, men det är grundläggande svenska värderingar som måste gälla oss alla. Liberalernas partiledare Simona Mohamsson kommenterar Buschs utspel: ”Burka och niqab är kvinnoförtryckande plagg som bygger på idén om att kvinnan inte ska synas i det offentliga rummet. För Liberalerna är det viktigt att de som utövar religiöst förtryck – till exempel slöjtvång – straffas av samhället”, skriver hon i ett sms till Aftonbladet. Förslaget att förbjuda burka och niqab i offentliga miljöer är en del av ett utvecklingsarbete som en arbetsgrupp inom KD tagit fram inför stämman senare i höst. Det har inte förankrats hos övriga Tidöpartier. Ebba Busch konstaterar att samhället varken kan eller ska kontrollera vad folk gör i hemmet. – Men burkan hör inte hemma i Sverige och vi ska inte bana väg för den. Vi ska mota Olle i grind här. Uppdaterad 12 oktober 2025 kl 16:04 Publicerad 12 oktober 2025 kl 12:09 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.svt.se/nyheter/utrikes/journalist-inslappt-i-gaza-efter-tva-ar-rafah-jamnat-med-marken",
        "title": "Javascript är avstängt",
        "language": "Swedish",
        "content": "De senaste två åren har Israel stoppat utländska journalister från att rapportera om kriget inifrån Gaza. Nu när vapenvilans första fas trätt i kraft kräver pressfrihetsorganisationer att journalister ska släppas in igen. Den schweiziska journalisten Emiliano Bos blev på fredagen en av de första att besöka Gaza efter vapenvilan – men då under strikta restriktioner. Emiliano Bos från den schweiziska tv-kanalen RSI besökte Gaza som inbäddad journalist tillsammans med den kritiserade stiftelsen Gaza Humanitarian Foundation (GHF). Det innebär att teamet får lov att filma platser och göra intervjuer med palestinier de träffar, men reser in under former som GHF kontrollerar. Han reste från gränsen i Kerem Shalom till en distributionsplats i Rafah. Tusentals palestinier hade kommit till platsen där säckar med lök och potatis delades ut. Före kriget levde mer än 200 000 palestinier i Rafah, i dag är det en spökstad i ruiner. ”Jämnad med marken är inte en bildlig utan en faktisk beskrivning”, uppger Emiliano Bos. Under det första dygnet sedan vapenvilan trädde i kraft har Israels militär dragit sig tillbaka från de centrala delarna av Gaza, men kontrollerar fortfarande mer än hälften av enklavens yta. På de platser som Israel lämnat har beväpnade Hamasstyrkor börjat synas på gatorna igen. Samtidigt har hundratusentals palestinier som flydde bombningarna i norra Gaza har börjat återvända. Under lördagen hittades 150 kroppar i ruinerna, enligt det Hamasstyrda civilförsvaret. Under kriget har pressfrihetsorganisationer och mediebolag upprepade gånger krävt att utländska journalister ska släppas in för att kunna rapportera. På fredagen kom Foreign Press Association (FPA) med nya krav på att släppa in journalister, med anledning av att striderna upphört. I Israel är stämningen hoppfull, säger SVT:s Mellanösternreporter Stina Blomgren som befinner sig i Tel Aviv. Senast måndag ska Hamas släppa de kvarvarande 48 israeliska gisslan, varav 20 tros vara i livet. På tisdag ska 250 palestinska fångar släppas fria. – Den första fasen i vapenvilan är ganska stabil. De svåra frågorna kommer i den andra fasen. Hur ska Hamas avväpnas och vem ska styra Gaza i framtiden? säger Stina Blomgren. Palestinier i Gaza som hon pratat med känner både lättnad och sorg, berättar hon. – De har sovit en natt utan bomber för första gången på länge. Men de känner också sorg för de har ägnat två år åt att bara försöka överleva. När situationen lugnar ner sig kommer sorgen över dem som inte överlevt. Uppdaterad 12 oktober 2025 kl 07:03 Publicerad 11 oktober 2025 kl 23:16 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.svt.se/nyheter/utrikes/hamas-gisslan-slapps-pa-mandag",
        "title": "Hamas: Gisslan släpps på måndag",
        "language": "Swedish",
        "content": "Terrorstämplade Hamas kommer att påbörja frisläppandet av israeliska gisslan på måndag morgon. Det säger det högt uppsatta Hamasbefälet Osama Hamdan till nyhetsbyrån AFP. Enligt uppgörelsen med Israel i torsdags ska Hamas frige gisslan senast klockan 12 på måndag lokal tid, skriver BBC. 48 personer som togs som gisslan för två år sedan är fortfarande kvar i Gaza. 20 av dem bedöms vara vid liv. De ska släppas i utbyte mot omkring 2 000 palestinska fångar – exakt vilka är en fråga som ännu diskuteras. Publicerad 12 oktober 2025 kl 07:16 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.svt.se/nyheter/inrikes/regeringen-vill-infora-skarp-aldersgrans-for-sociala-medier",
        "title": "Javascript är avstängt",
        "language": "Swedish",
        "content": "Regeringen ger i dag en utredare i uppdrag att undersöka möjligheterna att införa en skarp åldersgräns för sociala medier. Om det inte går ska utredaren även analysera om föräldrars rätt att lämna samtycke kan begränsas. – Det handlar om att ge barn deras barndom tillbaka, säger ministern. Frågan om åldersgräns för sociala medier är högaktuell och debatteras världen över. I december inför Australien en åldersgräns på 16 år för en lång rad populära sociala medier, och i Europa har länder som Frankrike och Spanien förespråkat liknande ålderskrav. Nu ger regeringen Lisa Englund Krafft, beredningschef vid Högsta förvaltningsdomstolen, i uppdrag att se över förutsättningarna i Sverige. Socialminister Jakob Forssmed (KD) säger att åldersgränser på 15 eller 16 år ofta nämns i diskussionerna i andra länder och ser en liknande lösning framför sig i Sverige. Om det inte bedöms möjligt att föreslå en åldersgräns för sociala medier ska utredaren också se över om föräldrar i framtiden bör få en mer begränsad möjlighet att ge sitt barn tillåtelse att använda dem. Du kan höra socialminister Jakob Forssmed (KD) berätta mer om uppdraget i videon ovan. Den del av utredningen som gäller förslag på en åldersgräns ska vara klar den 12 juni 2026. Källa: Regeringen Uppdaterad 10 oktober 2025 kl 12:16 Publicerad 10 oktober 2025 kl 12:13 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.svt.se/nyheter/utrikes/madagaskars-president-efter-gen-z-protesterna-kuppforsok-pagar",
        "title": "Javascript är avstängt",
        "language": "Swedish",
        "content": "Efter att en grupp soldater anslutit sig till de veckolånga protesterna i Madagaskar, ledda av ungdomsrörelsen ”Gen Z”, hävdar landets president att det nu pågår ”ett försök att ta makten med våld”. Den afrikanska önationen har skakats av protester sedan slutet av september, efter att ilska över strömavbrott och vattenbrist utvecklats till en bredare misstro mot landets styre. Demonstrationerna har letts av ”Gen Z”, en rörelse med en dödskalle i stråhatt som symbol och som även har startat sociala medier-organiserade protester i bland annat Nepal, Peru och Filippinerna. Vid flera tillfällen har det uppstått våldsamma sammandrabbningar med polisen i och enligt FN har minst 22 personer dödats och 100 skadats i samband med protesterna i Madagaskar. Militär och polis har tidigare även hindrat demonstranterna från att inta det symboliska 13 maj-torget i huvudstaden Antananarivo, men under lördagen fick de inte bara fri lejd – de kunde även marschera in sida vid sida med flera militärer. Däribland soldater från Madagaskars elitförband Capsat, vars ledare enligt The Guardian också höll ett tal inför den jublande folkmassan. Enligt Al Jazeera visades även stöd i en video på sociala medier publicerad av soldater vid den närliggande militärbasen. – Låt oss gå ihop – militär, militärpolis och polis – och vägra få betalt för att skjuta våra vänner, våra systrar och bröder, sade de bland annat. President Andry Rajoelina, som kom till makten 2009 efter en kupp understödd av just Capsat-förbandet, släppte under söndagsmorgonen ett officiellt uttalande som tycks vara en reaktion på utvecklingen. ”Republikens presidentämbete vill informera landet och det internationella samfundet att det för närvarande pågår ett försök att ta makten med våld, i strid mot konstitutionen och demokratiska principer”, skriver han enligt AFP . Exakt vad den bedömningen baseras på framgår inte, men presidenten lägger även till att ”dialog är den enda vägen framåt”. Publicerad 12 oktober 2025 kl 10:42 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.svt.se/nyheter/lokalt/varmland/en-till-sjukhus-efter-villabrand-i-kil-utreds-som-mordbrand",
        "title": "En till sjukhus efter villabrand i Kil – utreds som mordbrand",
        "language": "Swedish",
        "content": "En person är förd till sjukhus med oklart skadeläge efter en villabrand i Kil under söndagsmorgonen. Huset var helt övertänt när räddningstjänsten kom fram och det gick inte att rädda. Tidigt under söndagsmorgonen larmades räddningstjänsten till Högboda i Kils kommun. Det rörde sig om en villa som hade börjat brinna. Enligt polisen ska två personer ha tagit sig ut ur fastigheten och minst en person är förd till sjukvården men skadeläget är okänt. – En person verkar har hoppat ut från fönstret, säger Anders Dahlman, polisens presstalesperson. Enligt polisen ska ingen person vara kvar i byggnaden. Räddningstjänsten är kvar på plats under söndagen och polisen kommer genomföra teknisk undersökning. – Vi kommer inte kunna komma dit för undersökning idag, räddningstjänsten är inte klara och det är nog fortfarande för varmt där än. Så fort de är klara spärrar vi av för teknisk undersökning, säger Anders Dahlman på polisen under söndagsförmiddagen. Det är oklart varför branden uppstod. Händelsen utreds i nuläget som mordbrand. Uppdaterad 12 oktober 2025 kl 11:41 Publicerad 12 oktober 2025 kl 08:50 SVT:s nyheter ska stå för saklighet och opartiskhet. Det vi publicerar ska vara sant och relevant. Vid akuta nyhetslägen kan det vara svårt att få alla fakta bekräftade, då ska vi berätta vad vi vet – och inte vet. Läs mer om hur vi arbetar."
        },
    {
        "url": "https://www.svt.se/nyheter/inrikes/hatt-effekten-ar-utraderad",
        "title": "Javascript är avstängt",
        "language": "Swedish",
        "content": "Efter drygt fem månader med Anna-Karin Hatt vid rodret är Centerpartiet tillbaka på samma nivå som när hon valdes. Den ”Hatt-effekt” som partikamraterna hoppades på lyser med sin frånvaro. En förklaring är att de saknar en trovärdig parlamentarisk strategi för att få igenom sin politik. När partiledarna drabbar samman i kvällens Agenda gör de det i ljuset av att det är stiltje i opinionen. Trots veckor av budgetutspel, ett oroligt omvärldsläge och ett högt tonläge i sociala medier är alla förändringar inom felmarginalen. Värt att notera är dock att oppositionens övertag håller i sig. Och det trots att Tidöpartierna lagt en mycket expansiv valbudget där nära 50 miljarder går till att stärka hushållen. Men det miljardregnet känner väljarna inte av än. Många är fortsatt pressade och det finns en pessimism bland hushållen som missgynnar regeringen. Enligt den senaste mätningen från Novus tycker 61 procent av väljarna att Sverige är på väg åt fel håll. Det är en av de saker som Tidöpartierna behöver vända om de ska lyckas få en mandatperiod till i Rosenbad. För Moderaterna är utgångsläget dystert. Inte sedan 1978 har de legat så här lågt i oktober året före valet. Ett annat parti som har skäl att vara besvikna är Centerpartiet. När Anna-Karin Hatt (C) valdes till partiledare fanns stora förhoppningar på en tydlig ”Hatt-effekt”. Partistrategerna såg framför sig att hon skulle göra så kallade ”Magda-moderater” till ”Hatt-sossar”, alltså att välutbildade och välavlönade liberala storstadsväljare skulle föredra henne framför Magdalena Andersson (S). Men några sådana tendenser syns inte alls än – tvärtom har C åter ett flöde till S precis som tidigare under mandatperioden. En förklaring är att de har svårt att göra sig relevanta som minsta parti i opposition. En annan är det utomordentligt svaga stödet i samtliga sakfrågor. Det problemet är Anna-Karin Hatt högst medveten om, det är därför hon betonar vikten av sakpolitisk förnyelse. Men även om partiet lägger allt sitt krut på sakfrågorna går det inte att komma ifrån att de saknar en strategi för att få igenom dem. Det enda besked hon har gett är att all form av samverkan med SD är utesluten. Och skälet är enligt Hatt SD:s människosyn. Partiets tidigare insikt om att det är vanskligt att göra motståndet mot ett annat parti till sin främsta profilfråga verkar vara bortglömd. Det är elva månader till valet och mycket kan hända men om C blir minst på Anderssons sida har de ett svagt förhandlingsläge vid en eventuell vänsterseger. Särskilt förstås om de inte ens behövs för en rödgrön majoritet Publicerad 12 oktober 2025 kl 05:58 Slutsatserna är journalistens egna. SVT:s medarbetare agerar inte i något politiskt parti-, företags- eller intresseorganisations intresse. Det är förenligt med SVT:s sändningstillstånd §8 att ”kommentera och belysa händelser och skeenden”."
        },
    {
        "url": "https://www.sverigesradio.se/artikel/studie-vaccin-raddade-over-2-5-miljoner-liv",
        "title": "Studie: Vaccin räddade över 2,5 miljoner liv",
        "language": "Swedish",
        "content": "Enligt en ny studie förhindrade vaccin mot covid-19 över 2,5 miljoner dödsfall över hela världen mellan åren 2020 och 2024. Flest liv räddades bland äldre. Studien har utgått från globala uppgifter och är publicerad i Jama health forum. Ekot ekot@sverigesradio.se"
        },
    {
        "url": "https://www.sverigesradio.se/artikel/forskningsstudie-okad-utvinning-av-sand-hotar-hela-ekosystem",
        "title": "Forskningsstudie: Ökad utvinning av sand hotar hela ekosystem",
        "language": "Swedish",
        "content": "Användningen av sand i världen behöver begränsas för att skydda flora och fauna i flodbankar och havsbottnar. Det är en slutsats i en forskningsstudie publicerad i tidskriften One Earth. Årligen beräknas 50 miljarder ton sand utvinnas världen över. Anders Wennersten anders.wennersten@sverigesradio.se"
        }

]